export interface Product {
accepts_mercadopago: boolean,
address: any,
attributes: any,
available_quantity: number,
buying_mode: string,
catalog_product_id: any,
category_id: string,
condition: string
currency_id: string,
differential_pricing: any,
domain_id: string,
id: string,
installments: any,
listing_type_id:string,
official_store_id: any,
order_backend: number,
original_price: any,
permalink:string,
price: number
prices: any,
sale_price: any,
seller:any,
seller_address: any,
shipping: any,
site_id: string,
sold_quantity: number,
stop_time: string,
tags: any,
thumbnail: string,
thumbnail_id: string,
title: string,
use_thumbnail_id: boolean
}
